"""v6_add_history_info

Revision ID: 0e884bca64d3
Revises: ab4254ef9865
Create Date: 2025-05-03 16:35:44.153965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e884bca64d3'
down_revision: Union[str, None] = 'ab4254ef9865'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('driver', sa.Column('bithday', sa.Date(), nullable=True))
    op.add_column('history', sa.Column('work_hours', sa.Float(), nullable=True))
    op.add_column('history', sa.Column('spares', sa.String(), nullable=True))
    op.add_column('mechanic', sa.Column('bithday', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mechanic', 'bithday')
    op.drop_column('history', 'spares')
    op.drop_column('history', 'work_hours')
    op.drop_column('driver', 'bithday')
    # ### end Alembic commands ###
