"""v4_plus_hashed_parr

Revision ID: 19f6214d247d
Revises: 9fe6e9cd75ce
Create Date: 2025-03-21 21:08:14.005477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19f6214d247d'
down_revision: Union[str, None] = '9fe6e9cd75ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('driver', sa.Column('hashed_password', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'driver', ['email'])
    op.add_column('mechanic', sa.Column('hashed_password', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'mechanic', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mechanic', type_='unique')
    op.drop_column('mechanic', 'hashed_password')
    op.drop_constraint(None, 'driver', type_='unique')
    op.drop_column('driver', 'hashed_password')
    # ### end Alembic commands ###
