"""v5

Revision ID: 1ff73710fa5b
Revises: 19f6214d247d
Create Date: 2025-05-02 16:55:40.728086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ff73710fa5b'
down_revision: Union[str, None] = '19f6214d247d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car', sa.Column('power', sa.Integer(), nullable=True))
    op.add_column('car', sa.Column('v_dvig', sa.Float(), nullable=True))
    op.add_column('car', sa.Column('rasxod', sa.Integer(), nullable=True))
    op.add_column('car', sa.Column('type_kpp', sa.String(), nullable=True))
    op.add_column('car', sa.Column('gruzopod', sa.Integer(), nullable=True))
    op.add_column('driver', sa.Column('stag', sa.Integer(), nullable=True))
    op.alter_column('driver', 'phone',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    op.add_column('mechanic', sa.Column('stag', sa.Integer(), nullable=True))
    op.alter_column('mechanic', 'phone',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mechanic', 'phone',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('mechanic', 'stag')
    op.alter_column('driver', 'phone',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('driver', 'stag')
    op.drop_column('car', 'gruzopod')
    op.drop_column('car', 'type_kpp')
    op.drop_column('car', 'rasxod')
    op.drop_column('car', 'v_dvig')
    op.drop_column('car', 'power')
    # ### end Alembic commands ###
