"""v3_check_relation

Revision ID: 9fe6e9cd75ce
Revises: 213fe5a201ff
Create Date: 2025-03-19 16:49:05.919927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fe6e9cd75ce'
down_revision: Union[str, None] = '213fe5a201ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'driver', ['car_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'driver', type_='unique')
    # ### end Alembic commands ###
