"""v6

Revision ID: ab4254ef9865
Revises: 1ff73710fa5b
Create Date: 2025-05-02 16:57:41.816309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab4254ef9865'
down_revision: Union[str, None] = '1ff73710fa5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car', sa.Column('gos_nomer', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('car', 'gos_nomer')
    # ### end Alembic commands ###
